"""
Monte Carlo & TD(0) PREDICTION — drop the known model, estimate V^π from SAMPLED
experience. This is the first model-FREE method: the agent may only RESET and STEP
the world, it never gets to read p(s'|s,a) or r(s,a,s').

Recall exercise 2: with the model in hand, policy_evaluation just swept the Bellman
expectation backup (or you literally solved V = (I-γPπ)⁻¹rπ). That required knowing
P and r for every (s,a). Real agents almost never have that. All they have is a
stream of transitions (s, r, s'), generated by acting. So: how do you estimate the
value of a fixed policy π from samples alone?

TWO ANSWERS, and the bias/variance trade-off that splits them:

  MONTE CARLO (MC) — wait until the episode ENDS, then look at the actual return
    G_t = r_{t+1} + γ r_{t+2} + ... + γ^{T-1-t} r_T
  and average G_t over every time you visited state s. No bootstrapping, no model.
    V(s) ≈ average of observed returns from s.
  UNBIASED (G_t is a real sample of the true return) but HIGH VARIANCE — G_t
  depends on the whole tail of the episode (every random action and slip). And you
  must wait for termination, so no learning on never-ending tasks.

  TD(0) — don't wait. After a SINGLE step you already have a guess of the rest:
  V(s') itself. Bootstrap off it.
    target = r + γ V(s')            (the "TD target")
    V(s) <- V(s) + α [ r + γ V(s') - V(s) ]
  The bracket is the TD ERROR δ — exactly the (sample − prediction) nudge shape from
  the bandit update, now with a bootstrapped sample. BIASED (V(s') is your own
  current, wrong estimate) but LOW VARIANCE (one reward + one estimate, not a whole
  tail) and it learns ONLINE, step by step. This bootstrap is the seed of
  Q-learning / SARSA / DQN later.

So: MC ↔ TD(0) is the first appearance of the "bias/variance of the target" thread.
n-step and GAE(λ) later interpolate between these two extremes.

WHAT WE PREDICT: the value of the OPTIMAL policy from exercise 2. Satisfying
tie-back — MC and TD recover V* from samples alone, no model — and it gives us an
exact ground truth (the analytic linear solve) to grade your estimates against.

EXPLORING STARTS: a deterministic policy from a fixed start would only ever trace
one path, leaving most of the grid unvisited (and thus unestimated). So each
episode begins at a RANDOM non-terminal state — the simplest way to guarantee every
state's value gets sampled. (Real control fixes this differently, via ε-greedy
behaviour; that's exercise 4.)

ENV: the exercise-2 gridworld, imported and wrapped in a gym-like Sampler exposing
only reset()/step(a). The model P is still in there, but the algorithms below never
touch it — that's the whole point.
"""

from __future__ import annotations

import importlib.util
import pathlib

import numpy as np

# Import GridWorld + the exact ground-truth solver from exercise 2. (Module name
# starts with a digit, so a normal `import` won't parse — load it by path.)
_spec = importlib.util.spec_from_file_location(
    "mdp_dp", pathlib.Path(__file__).with_name("02_mdp_dp.py"))
mdp_dp = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(mdp_dp)
GridWorld = mdp_dp.GridWorld


class Sampler:
    """Gym-like wrapper that turns the MDP model into an EXPERIENCE stream.

    The DP algorithms in exercise 2 read env.P directly. The model-free algorithms
    here may only call reset()/step(a) — they see transitions, never probabilities.
    (Internally we sample from env.P; the algorithms just don't get to look.)
    """

    def __init__(self, env: GridWorld, rng: np.random.Generator):
        self.env = env
        self.rng = rng
        self._nonterminal = [s for s, cell in enumerate(env.states)
                             if cell not in env.terminals]
        self.s = None

    def reset(self) -> int:
        """Exploring start: begin at a uniformly random NON-terminal state."""
        self.s = int(self.rng.choice(self._nonterminal))
        return self.s

    def step(self, a):
        """One sampled transition from the current state. Returns (s', r, done).

        The ENV rolls its OWN dice — which action actually fires after the slip —
        then applies deterministic movement. It never builds a probability table;
        the agent just sees the single (s', r) that falls out. (Reuses the same
        _move + noise that exercise 2's model was built from, so the sampled
        dynamics match env.P exactly — by construction, not by luck.)
        """
        env = self.env
        cell = env.states[self.s]
        # slip: intended action w.p. 1-noise, each perpendicular w.p. noise/2.
        actual = int(self.rng.choice([a, (a + 1) % 4, (a - 1) % 4],
                                     p=[1 - env.noise, env.noise / 2, env.noise / 2]))
        nxt = env._move(cell, actual)            # wall/edge bounce lives in _move
        reward = env.terminals.get(nxt, env.step_reward)
        done = nxt in env.terminals
        self.s = env.s2i[nxt]
        return self.s, reward, done


# ---------------------------------------------------------------------------
# THE EXERCISE: fill in the three routines below. They may use ONLY sampler.reset(),
# sampler.step(a), and the given `policy` matrix — never env.P.
# ---------------------------------------------------------------------------

def generate_episode(sampler: Sampler, policy: np.ndarray,
                     rng: np.random.Generator,
                     max_steps: int = 1000) -> list[tuple[int, float, int, bool]]:
    """Roll out ONE episode following `policy`; return the raw experience both
    predictors learn from, as a list of transitions:

        [(s, r, s_next, done), ...]    one per step, in time order.

    `policy` is a stochastic matrix (nS, nA); sample the action a ~ policy[s].
    Start from sampler.reset(); stop when step() reports done (or max_steps hit).
    """
    episode = []
    s = sampler.reset()
    for _ in range(max_steps):
        a = int(rng.choice(sampler.env.nA, p=policy[s]))
        ns, r, done = sampler.step(a)
        episode.append((s, r, ns, done))
        s = ns
        if done:
            break
    return episode


def returns_from_episode(episode, gamma):
    """Discounted return G_t for every step, via one O(T) backward sweep.
    Returns a list aligned with `episode`: returns[t] is the return of state s_t."""
    G = 0.0
    out = [0.0] * len(episode)
    for t in range(len(episode) - 1, -1, -1):
        r = episode[t][1]
        G = r + gamma * G
        out[t] = G
    return out


def mc_prediction(env: GridWorld, sampler: Sampler, policy: np.ndarray,
                  gamma: float, num_episodes: int, rng: np.random.Generator,
                  first_visit: bool = True) -> np.ndarray:
    """Monte Carlo prediction of V^π — average observed returns G_t per state.

    Per episode, get every G_t from returns_from_episode (the O(T) backward sweep),
    then credit states. first_visit (default): only the FIRST occurrence of a state
    in the episode contributes — so samples are i.i.d. across episodes and the mean
    is unbiased for every n. first_visit=False is every-visit MC: also consistent,
    biased at finite n (within-episode returns are correlated suffixes).

    Returns V of shape (nS,).
    """
    returns_sum = np.zeros(env.nS)
    returns_cnt = np.zeros(env.nS)
    for _ in range(num_episodes):
        ep = generate_episode(sampler, policy, rng)
        G = returns_from_episode(ep, gamma)
        seen = set()
        for t, (s, _r, _ns, _d) in enumerate(ep):
            if first_visit and s in seen:
                continue                     # first-visit: skip repeat occurrences
            seen.add(s)
            returns_sum[s] += G[t]
            returns_cnt[s] += 1
    V = np.zeros(env.nS)
    nz = returns_cnt > 0
    V[nz] = returns_sum[nz] / returns_cnt[nz]
    return V


def td0_prediction(env: GridWorld, sampler: Sampler, policy: np.ndarray,
                   gamma: float, num_episodes: int, alpha: float,
                   rng: np.random.Generator) -> np.ndarray:
    """TD(0) prediction of V^π with a constant step size alpha.

    For every transition (s, r, s', done):
        target = r + gamma * V(s') * (1 - done)     # bootstrap; 0 past termination
        V(s)  += alpha * (target - V(s))            # the TD-error nudge

    The (1 - done) mask zeroes the bootstrap when s' is terminal — there's no future
    beyond the end. (Here V(terminal) stays 0 anyway, but the mask is the correct,
    general form and matters once V is a learned function.)

    Returns V of shape (nS,).
    """
    V = np.zeros(env.nS)
    for _ in range(num_episodes):
        for (s, r, ns, done) in generate_episode(sampler, policy, rng):
            target = r + gamma * V[ns] * (1.0 - done)   # no bootstrap past the end
            V[s] += alpha * (target - V[s])
    return V


# ---------------------------------------------------------------------------
# Self-check helpers (implemented for you) + the self-check itself.
# Run from the repo root:  uv run python rl/03_mc_td.py
# ---------------------------------------------------------------------------

def rms_error(V_hat: np.ndarray, V_true: np.ndarray,
              nonterminal: list[int]) -> float:
    """Root-mean-square error over the NON-terminal states (terminals are trivially
    0 for everyone and would only dilute the metric)."""
    diff = V_hat[nonterminal] - V_true[nonterminal]
    return float(np.sqrt(np.mean(diff ** 2)))


def render_values(env: GridWorld, V: np.ndarray) -> str:
    grid = [["  ·  " for _ in range(env.cols)] for _ in range(env.rows)]
    for (r, c) in env.walls:
        grid[r][c] = "  #  "
    for s, cell in enumerate(env.states):
        grid[cell[0]][cell[1]] = f"{V[s]:+.2f}"
    return "\n".join(" ".join(row) for row in grid)


if __name__ == "__main__":
    env = GridWorld()
    g = env.gamma
    rng = np.random.default_rng(0)
    sampler = Sampler(env, rng)

    # The policy we predict: the OPTIMAL policy from exercise 2's value iteration,
    # plus its EXACT value via the linear solve — our ground truth.
    opt_policy, _ = mdp_dp.value_iteration(env, g)
    V_true = mdp_dp.analytic_policy_value(env, opt_policy, g)
    nonterminal = sampler._nonterminal

    # --- 0) generate_episode produces a valid, terminating trajectory ----------
    ep = generate_episode(sampler, opt_policy, rng)
    assert len(ep) > 0, "episode should have at least one transition"
    assert ep[-1][3] is True or ep[-1][3] == 1, \
        "a finished episode's last transition should have done=True"
    assert all(0 <= s < env.nS and 0 <= ns < env.nS for (s, _r, ns, _d) in ep), \
        "episode visited an out-of-range state"
    assert env.states[ep[0][0]] not in env.terminals, \
        "exploring start should not begin on a terminal state"
    print(f"generate_episode rolls out a valid episode (len {len(ep)}) ✅")

    # --- 1) Monte Carlo prediction converges to the true V^π -------------------
    V_mc = mc_prediction(env, sampler, opt_policy, g, num_episodes=20000, rng=rng)
    err_mc = rms_error(V_mc, V_true, nonterminal)
    assert err_mc < 0.05, f"MC RMS error too high: {err_mc:.4f}"
    print(f"first-visit MC matches the analytic V^π  (RMS {err_mc:.4f}) ✅")

    # --- 2) TD(0) prediction converges to the true V^π -------------------------
    V_td = td0_prediction(env, sampler, opt_policy, g,
                          num_episodes=20000, alpha=0.05, rng=rng)
    err_td = rms_error(V_td, V_true, nonterminal)
    # looser bound than MC on purpose: constant-alpha TD doesn't converge to zero
    # error, it hovers around the truth (the step never shrinks) — that's expected.
    assert err_td < 0.07, f"TD(0) RMS error too high: {err_td:.4f}"
    print(f"TD(0) matches the analytic V^π            (RMS {err_td:.4f}) ✅")

    # --- 3) both model-free estimates agree with each other --------------------
    assert rms_error(V_mc, V_td, nonterminal) < 0.07, \
        "MC and TD(0) should land on the same V^π"
    print("MC and TD(0) agree (both recover V* from samples, no model) ✅")

    print("\nground truth V^π (optimal policy):")
    print(render_values(env, V_true))
    print("\nMonte Carlo estimate:")
    print(render_values(env, V_mc))
    print("\nTD(0) estimate:")
    print(render_values(env, V_td))
    print("\nmodel-free prediction works ✅")
